
cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'vim'
brew 'grep'
brew 'openssh'
brew 'zsh'
brew 'ack'
brew 'git'
brew 'imagemagick'
brew 'wget'
brew 'nginx'
brew 'pyenv'
brew 'tmux'
brew 'the_silver_searcher'

cask 'appcleaner'
cask 'firefox'
cask 'google-chrome'
cask 'transmission'
cask 'vlc'
cask 'macpass'
cask 'dropbox'
cask 'visual-studio-code'
cask 'imageoptim'
cask 'rectangle'
